"""empty message

Revision ID: 600351e584df
Revises: 
Create Date: 2022-07-27 14:22:01.819947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '600351e584df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment', 'guests', ['comment_guest'], ['guest_id'])
    op.create_foreign_key(None, 'guest_gift', 'guests', ['g_guestid'], ['guest_id'])
    op.create_foreign_key(None, 'guest_gift', 'gifts', ['g_giftid'], ['gift_id'])
    op.alter_column('guests', 'guest_image',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('lga', 'state_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('lga', 'lga_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("''"))
    op.create_foreign_key(None, 'lga', 'state', ['state_id'], ['state_id'])
    op.create_foreign_key(None, 'order_details', 'orders', ['det_orderid'], ['order_id'])
    op.create_foreign_key(None, 'order_details', 'uniform', ['det_itemid'], ['uni_id'])
    op.create_foreign_key(None, 'orders', 'guests', ['order_by'], ['guest_id'])
    op.create_foreign_key(None, 'payment', 'orders', ['pay_orderid'], ['order_id'])
    op.create_foreign_key(None, 'payment', 'guests', ['pay_guestid'], ['guest_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'order_details', type_='foreignkey')
    op.drop_constraint(None, 'order_details', type_='foreignkey')
    op.drop_constraint(None, 'lga', type_='foreignkey')
    op.alter_column('lga', 'lga_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('lga', 'state_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('guests', 'guest_image',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.drop_constraint(None, 'guest_gift', type_='foreignkey')
    op.drop_constraint(None, 'guest_gift', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    # ### end Alembic commands ###
